name: Deploy or Destroy

on:
  workflow_dispatch:
    inputs:
      destroy_flag:
        description: 'Flag to trigger destroy'
        required: true
        default: "false"

jobs:
  deploy_or_destroy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # Step 4: Initialize Terraform with the remote backend
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ github.workspace }}/infra

      # Step 5: Apply or Destroy based on input flag
      - name: Terraform Apply or Destroy
        run: |
          if [ "${{ github.event.inputs.destroy_flag }}" == "true" ]; then
            terraform destroy -auto-approve
          else
            terraform apply -auto-approve
          fi
        working-directory: ${{ github.workspace }}/infra
